website/forms.py
from flask import Flask
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, EqualTo, Email
from wtforms import ValidationError


from flask_login import current_user
from website.models import User


class LoginForm(FlaskForm):
    email = StringField('Email: ', validators=[Email(), DataRequired()])
    password = PasswordField('Password: ', validators=[DataRequired()])
    submit = SubmitField('Login')


class RegistrationForm(FlaskForm):

    name = StringField(label=None, validators=[DataRequired()])
    email = StringField(label=None, validators=[DataRequired(), Email()])
    username = StringField(label=None, validators=[DataRequired()])
    password = PasswordField(label=None, validators=[DataRequired(), EqualTo(
        'pass_confirm', message="Passwords must match!")])
    pass_confirm = PasswordField(
        'Confirm Password: ', validators=[DataRequired()])
    submit = SubmitField('Register')

    def validate_email(self, email):
        if User.query.filter_by(email=self.email.data).first():
            raise ValidationError('Email has been already registered!')

    def validate_username(self, username):
        if User.query.filter_by(username=self.username.data).first():
            raise ValidationError('Username has been taken!')

website/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

login_manager = LoginManager()

app = Flask(__name__)

secret = os.urandom(16)
app.config['SECRET_KEY'] = secret

basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + \
    os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app, db)

# login_manager.init_app(app)
# login_manager.login_view = 'login'

from website.error_pages.handlers import error_pages
from website.portfolio.views import portfolio

app.register_blueprint(error_pages)
app.register_blueprint(portfolio,url_prefix='/portfolio')

website/portfolio/views.py
from flask import Blueprint, render_template

portfolio = Blueprint('portfolio', __name__)


@portfolio.route('/cgiu')
def portfolio_cgiu():
    return render_template('portfolio/cgiu.html')


@portfolio.route('/ges')
def portfolio_ges():
    return render_template('portfolio/ges.html')


@portfolio.route('/masterpiece')
def portfolio_masterpiece():
    return render_template('portfolio/masterpiece.html')


@portfolio.route('/openiit18')
def portfolio_openiit18():
    return render_template('portfolio/openiit18.html')


@portfolio.route('/prakriti')
def portfolio_prakriti():
    return render_template('portfolio/prakriti.html')


@portfolio.route('/r3')
def portfolio_r3():
    return render_template('portfolio/r3.html')


@portfolio.route('/rth')
def portfolio_rth():
    return render_template('portfolio/rth.html')


@portfolio.route('/siemens')
def portfolio_siemens():
    return render_template('portfolio/siemens.html')

website/templates/inner-page.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>ProDex IIT Kharapur</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{{url_for('static',filename='assets/img/favicon.png')}}" rel="icon">
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{{url_for('static',filename='assets/vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
  <link href="{{url_for('static',filename='assets/vendor/icofont/icofont.min.css')}}" rel="stylesheet">
  <link href="{{url_for('static',filename='assets/vendor/boxicons/css/boxicons.min.css')}}" rel="stylesheet">
  <link href="{{url_for('static',filename='assets/vendor/remixicon/remixicon.css')}}" rel="stylesheet">
  <link href="{{url_for('static',filename='assets/vendor/venobox/venobox.css')}}" rel="stylesheet">
  <link href="{{url_for('static',filename='assets/vendor/owl.carousel/assets/owl.carousel.min.css')}}" rel="stylesheet">
  <link href="{{url_for('static',filename='assets/vendor/aos/aos.css')}}" rel="stylesheet">

  <!-- Main CSS File -->
  <link href="{{url_for('static',filename='assets/css/style.css')}}" rel="stylesheet">

</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top header-inner-pages">
    <div class="container d-flex align-items-center">

      <!-- <h1 class="logo mr-auto"><a href="index.html">ProDex</a></h1> -->
      <!-- Uncomment below if you prefer to use an image logo -->
      <a href="index.html" class="logo mr-auto"><img src="assets/img/pdx.png" alt="" class="img-fluid"></a>

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li><a href="index.html">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#services">Services</a></li>
          <li><a href="#portfolio">Portfolio</a></li>
          <li><a href="#team">Team</a></li>
          <li class="drop-down"><a href="">Drop Down</a>
            <ul>
              <li><a href="javascript:;">Drop Down 1</a></li>
              <li class="drop-down"><a href="javascript:;">Deep Drop Down</a>
                <ul>
                  <li><a href="javascript:;">Deep Drop Down 1</a></li>
                  <li><a href="javascript:;">Deep Drop Down 2</a></li>
                  <li><a href="javascript:;">Deep Drop Down 3</a></li>
                  <li><a href="javascript:;">Deep Drop Down 4</a></li>
                  <li><a href="javascript:;">Deep Drop Down 5</a></li>
                </ul>
              </li>
              <li><a href="javascript:;">Drop Down 2</a></li>
              <li><a href="javascript:;">Drop Down 3</a></li>
              <li><a href="javascript:;">Drop Down 4</a></li>
            </ul>
          </li>
          <li><a href="#contact">Contact</a></li>

        </ul>
      </nav><!-- .nav-menu -->

      <a href="#about" class="get-started-btn scrollto">Get Started</a>

    </div>
  </header><!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <ol>
          <li><a href="index.html">Home</a></li>
          <li>Inner Page</li>
        </ol>
        <h2>Inner Page</h2>

      </div>
    </section><!-- End Breadcrumbs -->

    <section class="inner-page">
      <div class="container">
        <p>
          Example inner page template
        </p>
      </div>
    </section>

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">

    <!-- <div class="footer-newsletter">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-6">
            <h4>Join Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>
        </div>
      </div>
    </div> -->

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>ProDex</h3>
            <p>
              Indian Institute Of Technology Kharagpur <br>
              West-Bengal, 721302<br>
              India <br><br>
              <strong>LinkedIn: @</strong>ProDex IIT Kharagpur<br>
              <strong>Email:</strong> prodex.iitkgp@gmail.com<br>
            </p>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="javascript:;">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#about">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#services">What We Do</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#portfolio">Portfolio</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#contact">Contact Us</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Areas Of Work</h4>
            <ul>
              <li><i class="bx bx-medal"></i> Hardware Modelling</li>
              <li><i class="bx bx-medal"></i> Product Management</li>
              <li><i class="bx bx-medal"></i> Design and Media</li>
              <li><i class="bx bx-medal"></i> Web/App Development</li>
              <!-- <li><i class="bx bx-chevron-right"></i> <a href="javascript:;">Graphic Design</a></li> -->
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Social Networks</h4>
            <p>Get in touch with us!</p>
            <div class="social-links mt-3">
              <!-- <a href="javascript:;" class="twitter"><i class="bx bxl-twitter"></i></a> -->
              <a href="https://www.facebook.com/prodex.iitkgp" class="facebook"><i class="bx bxl-facebook"></i></a>
              <!-- <a href="javascript:;" class="instagram"><i class="bx bxl-instagram"></i></a> -->
              <!-- <a href="javascript:;" class="google-plus"><i class="bx bxl-skype"></i></a> -->
              <a href="https://www.linkedin.com/company/prodex-iit-kharagpur/about/" class="linkedin"><i class="bx bxl-linkedin"></i></a>
              <!-- <a href="https://github.com/ProDex-IIT-Kharagpur" class="github"><i class="bx bxl-github"></i></a> -->
              <a href="https://www.youtube.com/channel/UCMaLD7pBmxgstEuirySdoDQ" class="youtube"><i class="bx bxl-youtube"></i></a>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="container footer-bottom clearfix">
      <div class="copyright">
        &copy; Copyright <strong><span>ProDex</span></strong> All Rights Reserved
      </div>
      <div class="credits">

        Designed with ❤ by <a href="javascript:;">ProDex IIT-Kharagpur</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="javascript:;" class="back-to-top"><i class="ri-arrow-up-line"></i></a>
  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="{{url_for('static',filename='assets/vendor/jquery/jquery.min.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/jquery.easing/jquery.easing.min.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/php-email-form/validate.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/waypoints/jquery.waypoints.min.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/isotope-layout/isotope.pkgd.min.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/venobox/venobox.min.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/owl.carousel/owl.carousel.min.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/aos/aos.js')}}"></script>

  <!-- Template Main JS File -->
  <script src="{{url_for('static',filename='assets/js/main.js')}}"></script>
  <!-- Bootstrap core JavaScript -->
  <script src="{{url_for('static',filename='assets/vendor/jquery/jquery.min.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

</body>

</html>

website/templates/login.html
<!DOCTYPE html>
<html>

<head>
  <title>Login Page</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
  <!--Custom styles-->
  <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='assets/css/login_style.css')}}">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>

<body>
  <div class="container h-100">
    <div class="d-flex justify-content-center h-100">
      <div class="user_card">
        <div class="d-flex justify-content-center">
          <div class="brand_logo_container">
            <img src="{{url_for('static',filename='assets/img/PROFILE_PIC_flat.png')}}" class="brand_logo" alt="Logo">
          </div>
        </div>
        <div class="d-flex justify-content-center form_container">
          <form>
            <div class="input-group mb-3">
              <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-envelope"></i></span>
              </div>
              <input type="text" name="" class="form-control input_user" value="" placeholder="email-id">
            </div>
            <div class="input-group mb-2">
              <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-key"></i></span>
              </div>
              <input type="password" name="" class="form-control input_pass" value="" placeholder="password">
            </div>
            <div class="form-group">
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="customControlInline">
                <label class="custom-control-label" for="customControlInline">Remember me</label>
              </div>
            </div>
            <div class="d-flex justify-content-center mt-3 login_container">
              <button type="button" name="button" class="btn login_btn">Login</button>
            </div>
          </form>
        </div>

        <div class="mt-4">
          <div class="d-flex justify-content-center links">
            Don't have an account? <a href="{{url_for('signup')}}" class="ml-2" style="colour:white">Sign Up</a>
          </div>
          <div class="d-flex justify-content-center links" style="colour:white">
            <a href="#">Forgot your password?</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

</html>

website/templates/portfolio/cgiu.html
{% extends "portfolio_base.html" %}
{% block content %}


<main id="main">

  <!-- ======= Breadcrumbs ======= -->
  <section id="breadcrumbs" class="breadcrumbs">
    <div class="container">

      <ol>
        <li><a href="index.html">Home</a></li>
        <li>Portfolio Details</li>
      </ol>
      <h2>Portfolio Details: Clinton Foundation - CGI U 2018</h2>

    </div>
  </section><!-- End Breadcrumbs -->

  <!-- ======= Portfolio Details Section ======= -->
  <section id="portfolio-details" class="portfolio-details">
    <div class="container">

      <div class="portfolio-details-container">

        <div class="owl-carousel portfolio-details-carousel">
          <img src="{{url_for('static',filename='assets/img/portfolio/cgiu1.jpg')}}" class="img-fluid" alt="">
          <!-- <img src="assets/img/portfolio/siemens2.png" class="img-fluid" alt="">
            <img src="assets/img/portfolio/siemens1.jpg" class="img-fluid" alt=""> -->
        </div>

        <div class="portfolio-info">
          <h3>Event information</h3>
          <ul>
            <li><strong>Event Name</strong>: Clinton Foundation - CGI U 2018</li>
            <li><strong>Event Venue</strong>: Univeristy Of Chicago, USA</li>
            <li><strong>Event date</strong>: 19-21 October, 2018</li>
            <li><strong>Event URL</strong>: <a href="https://www.clintonfoundation.org/clinton-global-initiative/meetings/cgi-university/2018">Click to Visit</a></li>
          </ul>
        </div>

      </div>

      <div class="portfolio-description">
        <h2>CGI U - University of Chicago</h2>
        <p>
          Team ProDex was selected to participate in the Clinton Global Initiative University (CGI U) hosted at the University of Chicago from 19th October to 21st October, 2018. Amidst the enthusiasm among the fellow attendees and the inspiring
          speeches given by distinguished leaders including former US President Clinton, the team felt ecstatic to present two of their projects focussing on the problems of pollution and food wastage in India.
          <br><br> CGIU is a platform to compete and collaborate between innovative solutions for tackling pressing global challenges through knowledge building with topic experts and university representatives from around 200 countries. With the
          enriching exposure at CGI U, the team is more focused than ever to work towards their commitment to “turning ideas into reality”.
        </p>
      </div>

    </div>
  </section><!-- End Portfolio Details Section -->

</main><!-- End #main -->

{% endblock %}

website/templates/portfolio_base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>ProDex IIT Kharagpur</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{{url_for('static',filename='assets/img/favicon.png')}}" rel="icon">
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{{url_for('static',filename='assets/vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
  <link href="{{url_for('static',filename='assets/vendor/icofont/icofont.min.css')}}" rel="stylesheet">
  <link href="{{url_for('static',filename='assets/vendor/boxicons/css/boxicons.min.css')}}" rel="stylesheet">
  <link href="{{url_for('static',filename='assets/vendor/remixicon/remixicon.css')}}" rel="stylesheet">
  <link href="{{url_for('static',filename='assets/vendor/venobox/venobox.css')}}" rel="stylesheet">
  <link href="{{url_for('static',filename='assets/vendor/owl.carousel/assets/owl.carousel.min.css')}}" rel="stylesheet">
  <link href="{{url_for('static',filename='assets/vendor/aos/aos.css')}}" rel="stylesheet">

  <!-- Main CSS File -->
  <link href="{{url_for('static',filename='assets/css/style.css')}}" rel="stylesheet">

</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top header-inner-pages">
    <div class="container d-flex align-items-center">

      <!-- Uncomment below if you prefer to use an image logo -->
      <a href="{{url_for('index')}}" class="logo mr-auto"><img src="{{url_for('static',filename='assets/img/brand.png')}}" alt="" class="img-fluid"></a>

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li><a href="{{url_for('index')}}">Home</a></li>
          <li><a href="{{url_for('blog_posts')}}">Blogs</a></li>
          <!-- <li><a href="#about">About</a></li>
          <li><a href="#services">Services</a></li>
          <li class="active"><a href="#portfolio">Portfolio</a></li>
          <li><a href="#team">Team</a></li> -->
          <li class="drop-down"><a href="javascript:;">Portfolio</a>
            <ul>
              <li><a href="{{url_for('portfolio.portfolio_siemens')}}">Siemens Hackathon 2019</a></li>
              <!-- <li class="drop-down"><a href="javascript:;">Deep Drop Down</a>
                <ul>
                  <li><a href="javascript:;">Deep Drop Down 1</a></li>
                  <li><a href="javascript:;">Deep Drop Down 2</a></li>
                  <li><a href="javascript:;">Deep Drop Down 3</a></li>
                  <li><a href="javascript:;">Deep Drop Down 4</a></li>
                  <li><a href="javascript:;">Deep Drop Down 5</a></li>
                </ul>
              </li> -->
              <li><a href="{{url_for('portfolio.portfolio_openiit18')}}">Open IIT 2018</a></li>
              <li><a href="{{url_for('portfolio.portfolio_cgiu')}}">CGI U 2018</a></li>
              <li><a href="{{url_for('portfolio.portfolio_prakriti')}}">Prakriti Prod-D 2018</a></li>
              <li><a href="{{url_for('portfolio.portfolio_rth')}}">Rural Tech. Hackathon 2018</a></li>
              <li><a href="{{url_for('portfolio.portfolio_ges')}}">GES Product Design 2018</a></li>
              <li><a href="{{url_for('portfolio.portfolio_masterpiece')}}">Masterpiece Dubai 2017</a></li>
              <li><a href="{{url_for('portfolio.portfolio_r3')}}">R3 IIT Bombay 2017</a></li>
            </ul>
          </li>
          <!-- <li><a href="#contact">Contact</a></li> -->

        </ul>
      </nav><!-- .nav-menu -->

      <a href="{{url_for('signup')}}" class="get-started-btn">Sign Up</a>

    </div>
  </header><!-- End Header -->

  {% block content %}

  {% endblock %}


  <!-- ======= Footer ======= -->
  <footer id="footer">

    <!-- <div class="footer-newsletter">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-6">
            <h4>Join Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>
        </div>
      </div>
    </div> -->

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3><span style="color: #31A9E1;">P</span>ro<span style="color: #31A9E1;">D</span>ex</h3>
            <p>
              Indian Institute Of Technology Kharagpur <br>
              West-Bengal, 721302<br>
              India <br><br>
              <strong>LinkedIn: @</strong>ProDex IIT Kharagpur<br>
              <strong>Email:</strong> prodex.iitkgp@gmail.com<br>
            </p>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{{url_for('index')}}">Home</a></li>
              <!-- <li><i class="bx bx-chevron-right"></i> <a href="#about">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#services">What We Do</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#portfolio">Portfolio</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#contact">Contact Us</a></li> -->
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Areas Of Work</h4>
            <ul>
              <li><i class="bx bx-medal"></i> Hardware Modelling</li>
              <li><i class="bx bx-medal"></i> Product Management</li>
              <li><i class="bx bx-medal"></i> Design and Media</li>
              <li><i class="bx bx-medal"></i> Web/App Development</li>
              <!-- <li><i class="bx bx-chevron-right"></i> <a href="javascript:;">Graphic Design</a></li> -->
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Social Networks</h4>
            <p>Get in touch with us!</p>
            <div class="social-links mt-3">
              <!-- <a href="javascript:;" class="twitter"><i class="bx bxl-twitter"></i></a> -->
              <a href="https://www.facebook.com/prodex.iitkgp" class="facebook"><i class="bx bxl-facebook"></i></a>
              <!-- <a href="javascript:;" class="instagram"><i class="bx bxl-instagram"></i></a> -->
              <!-- <a href="javascript:;" class="google-plus"><i class="bx bxl-skype"></i></a> -->
              <a href="https://www.linkedin.com/company/prodex-iit-kharagpur/about/" class="linkedin"><i class="bx bxl-linkedin"></i></a>
              <!-- <a href="https://github.com/ProDex-IIT-Kharagpur" class="github"><i class="bx bxl-github"></i></a> -->
              <a href="https://www.youtube.com/channel/UCMaLD7pBmxgstEuirySdoDQ" class="youtube"><i class="bx bxl-youtube"></i></a>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="container footer-bottom clearfix">
      <div class="copyright">
        &copy; Copyright <strong><span>ProDex</span></strong> All Rights Reserved
      </div>
      <div class="credits">

        Designed with ❤ by <a href="javascript:;">ProDex IIT-Kharagpur</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="javascript:;" class="back-to-top"><i class="ri-arrow-up-line"></i></a>
  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="{{url_for('static',filename='assets/vendor/jquery/jquery.min.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/jquery.easing/jquery.easing.min.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/php-email-form/validate.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/waypoints/jquery.waypoints.min.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/isotope-layout/isotope.pkgd.min.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/venobox/venobox.min.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/owl.carousel/owl.carousel.min.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/aos/aos.js')}}"></script>

  <!-- Template Main JS File -->
  <script src="{{url_for('static',filename='assets/js/main.js')}}"></script>
  <!-- Bootstrap core JavaScript -->
  <script src="{{url_for('static',filename='assets/vendor/jquery/jquery.min.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

</body>

</html>